_veh = "B_UAV_02_dynamicLoadout_F" createVehicle (player modeltoworld [0,5,250]);
createVehiclecrew _veh;
_veh engineOn true;
_dir = getdir player;
_veh setDir _dir;
_veh setPosASL [getPosASL player select 0, (getPosASL player select 1) + 10, 1000];
_speed = 500;
_veh setVelocity [(sin _dir * _speed),(cos _dir * _speed), 0];
_veh engineOn true;
_veh flyInHeight 1000;
player additem "B_UavTerminal";
player assignItem "B_UavTerminal";
player connectterminaltouav _veh;
_veh setDamage 0; 
_veh allowdamage false;
_veh setcaptive true;
_veh setfuel 1; 
_veh setVehicleAmmo 1;
_veh allowdamage false;
getconnecteduav player addAction ["Repair and Rearm UAV",{getconnecteduav player setfuel 1; getconnecteduav player setVehicleAmmo 1; getconnecteduav player setDamage 0;}];
_veh addWeaponTurret ["missiles_Jian",[0]];
_veh addMagazineTurret ["4Rnd_LG_Jian",[0]];
_veh addWeaponTurret ["missiles_ASRAAM",[0]];
_veh addMagazineTurret ["4Rnd_AAA_missiles",[0]];
_veh addWeaponTurret ["rhs_weap_kh55sm_Launcher",[0]];
_veh addMagazineTurret ["rhs_mag_kh55sh_6",[0]];
["UAV Support On Station, Control With your UAV Terminal"] call Toni_fnc_structuredhint;